### ISSUE TITLE
Add sbt-dependency-graph

### ISSUE THREAD

**Issue by janm399** [cakesolutions/sbt-cake#20]
It'd be really useful to include the https://github.com/jrudolph/sbt-dependency-graph in the standard set of plugins.

**Comment by dhpiggott** [comment]
I used to add it (and sbt-updates) as plugins to every build I created. Then someone* suggested to me that the better place to add plugins such as those two is as machine-local SBT-global plugins; the reason being that they are informational only, so adding them as SBT-local plugins can be a distraction.

So now I just have this:
```
➜  ~ cat .sbt/0.13/plugins/build.sbt
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
```

\*I can't remember who it was for sure, but I want to say it was @fommil because I do remember that it was in https://github.com/cakesolutions/iot-demo/pull/64 that those two plugins were removed from the iot-demo.

I do now prefer the SBT-global approach, though I know there arguments for and against both ways.

**Comment by fommil** [comment]
Yup, that was me. Means you get it everywhere. Check my dotfiles for a way to do it that is java 6 safe.

**Comment by janm399** [comment]
That makes sense, especially with @fommil's comment on https://github.com/jrudolph/sbt-dependency-graph/issues/120

**Comment by fommil** [comment]
https://github.com/fommil/dotfiles/blob/master/.sbt/0.13/plugins/plugins.sbt
