### ISSUE TITLE
CI fatal-warnings setting

### ISSUE THREAD

**Issue by simonsouter** [cakesolutions/sbt-cake#54]
In CakeStandardsPlugin, this setting is questionable:

sys.env
              .get("CI")
              .fold(Seq.empty[String])(_ => Seq("-Xfatal-warnings"))

i.e. failing a CI build for compiler warnings that successfully build locally is not practicle in my opinion.

**Comment by carlpulley** [comment]
Are you suggesting that we should always have `-Xfatal-warnings` enabled by default?

**Comment by simonsouter** [comment]
No, it generates too many false positives.  Differing strictness per environment is certainly not convenient though.

**Comment by carlpulley** [comment]
If I understand yourself correctly, then you are asking for the setting `-Xfatal-warnings` to be off permanently?

Your argument for supporting this action is that you believe that because this setting is off locally (by default this is currently so in local dev environments), developers are led to believe that all is good and then discover that the build fails in CI/Jenkins environments?

If this is an accurate summary of your position, then this is something we should not be supporting. IMHO, we should enable this setting permanently (that way your concern over surprises between local dev and CI environments ceases). Every compiler warning in a production environment is definitely an error - it indicates that the developer does not have full control over their build process.

**Comment by simonsouter** [comment]
Im in disagreement to the general approach of enforcing practices (formatting, test coverage and lint warnings etc).  Devs (experts) should be empowered to make correct decisions and tooling should only support that.  i.e. we should have the opportunity to choose when to address technical debt, code coverage and address lint warnings etc. i.e. a practical agile methodology.

"Every compiler warning in a production environment is definitely an error" - some of the compiler warnings, such as 'warn-value-discard', can not be described as 'production errors'.  That is purely static analysis, which is useful to be made aware of, but I certainly don't want this to be enforced.

The sbt_cake tooling generally needs to be more lightweight and less intrusive going forward...

**Comment by Slakah** [comment]
The amount of false positives generated from the scalac linting flags, are pretty high, and ideally changes like this shouldn't be added as part of a patch version bump.

See: https://github.com/cakesolutions/sbt-cake/commit/84649f660eb4a2571a09d7014b2ab9ffab7884b5

**Comment by carlpulley** [comment]
Commit 84649f6 was made before any teams had started using sbt-cake. 

@Slakah do you have examples of the false positives you're noticing here? I'm asking as identifying the false positives others experience might help myself determine if the issues here are related to warnings being promoted to errors or down to project specifics.

**Comment by carlpulley** [comment]
Following a discussion of this ticket, the proposed change here is to change the build behaviour so that in local dev environments, warnings always get escalated to errors (just like in CI environments). So that devs may ease any perception of pain, we'll still provide an environment variable override that allows this setting to be disabled during debug runs.
